[package]
name = "ports"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bundle = { version = "0.1.0", path = "../bundle" }
gate ={ version = "0.1.0", path = "../gate" }
clap = { version = "4.0.29", features = ["derive"] }
compress-tools = { version = "0.14.0", features = ["blocking"] }
curl = "0.4.44"
directories = "4.0.1"
fs_extra = "1.2.0"
kdl = "4.6.0"
log = "0.4.17"
microtemplate = "1.0.3"
miette = { version = "4.3.0", features = ["fancy"] }
rustyline = { version = "10.0.0", features = ["case_insensitive_history_search"] }
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.91"
sha2 = "0.10.6"
thiserror = "1.0.38"
url = "2.3.1"
dotenv = { version = "0.15.0" }
oauth2 = "4.3.0"
console = "0.15.5"
reqwest = { version = "0.11.14", features = ["json", "blocking", "gzip", "brotli"] }
graphql_client = "0.12.0"
file-matcher = { version = "0.7.0", features = ["regex", "copier", "serde"] }
shellexpand = "3.0.0"
lazy_static = "1.4.0"
config = "0.13.3"
repology = { version = "0.1.0", path = "../repology" }

